### ISSUE TITLE
Which file format should I use?

### ISSUE THREAD

**Issue by lxly9** [emilyploszaj/chime#24]
As my question states, I am unsure which file format to use to port over my already existing OptiFine textures over to chime. Do I need to use .properties or a .mcmeta file?

**Comment by lxly9** [comment]
Hey, I found a different way to use my textures, though I'd love to have the boiling water bucket ;)

**Comment by emilyploszaj** [comment]
Chime uses the vanilla item models. It's extensively documented on the wiki with examples.
