### ISSUE TITLE
Utilizing Wildcards to find portions of names

### ISSUE THREAD

**Issue by Ghiojo** [emilyploszaj/chime#26]
I think that something that currently holds Chime back a lot is the ability to look for a portion of a name by using any sort of wildcards, similar to how Optifine CIT allows for doing "Name*" so you could look for any item that starts with "Name".

This allows for much better customization and I think it would help the mod gain more popularity.

**Comment by emilyploszaj** [comment]
The wiki has a reasonably detailed documentation on how strings work. A notable inclusion is every string can be matched with regex by surrounding it with `/`. For example, matching a name that starts with "Name" would be `/Name.*/`. However, compared to wildcards, regex is a much more popular standard, and supports much more than generic wildcard matching. For instance, if you want to match names that are only vowels and at least 6 characters long, `/[aeiou]{6,}/`.
