### ISSUE TITLE
Crashing when using wildcard * in Regex for strings

### ISSUE THREAD

**Issue by Kamorzy** [emilyploszaj/chime#30]
When trying to make armor labelled for invisibility target the blank texture file, it crashes for anything using a wildcard (*). It works for other more specific regex. The following is the predicate I'm using:

```
{
  "predicate": {
   "name":"/*Invis*/"
  },
  "texture": "overrides/armor/diamond_layer_1"
}
```

**Comment by emilyploszaj** [comment]
`*` is not a wildcard in regex, it's a count modifier. The regex wildcard is `.`

**Comment by Kamorzy** [comment]
Thank you for your quick reply, I noticed that just now as well. My bad.
