### ISSUE TITLE
[Suggestion] Create lang folder in Code

### ISSUE THREAD

**Issue by Rad233** [emilyploszaj/chime#32]
Creating a lang folder in Code can help translators submitting localizations efficiently.
Here's zh_cn localization.
[zh_cn.json.txt](https://github.com/emilyploszaj/chime/files/10242529/zh_cn.json.txt)

**Comment by emilyploszaj** [comment]
I believe you are confusing Chime with another mod, my mod doesn't add any blocks or items like what you are translating.
