### ISSUE TITLE
Regex issues

### ISSUE THREAD

**Issue by bangetto** [emilyploszaj/chime#34]
Recently I translated a resources pack from optifine to Chime and the owner of the resources pack wanted to be non-case sensitive and that you can put things around it. The simplest way to add non-case sensitivity using regex is with `/.../i` but Chime doesn't supports that so I had to manually specify every single character that it can be uppercase and lover case like this: `(L|l)`.
It was **unnecessarily painful**, please fix this!

**Comment by emilyploszaj** [comment]
`/(?i)some/` will match `Some`, `SOME`, `some` etc.
